C stegall
Section508Coordinators/baselinealignment pull request #111
Opened 2021-09-22 16:36 UTC by CJStegall

TC8.1-3

2021-11-17 22:39 UTC, kengdoj commented on TC8.1-3-pass-2
> +| 8.1-2| If the contrast ratio is less than 4.5:1, check that the ratio is at least 3:1 AND the font meets one of the following criteria: [SC 1.4.3]| The contrast is at least 14 point (18.62 pixels)
Please add the first test instruction and the contrast found in the Result column
8.1-1 | Determine the contrast ratio of foreground text and background. | (enter contrast ratio found |

2021-11-17 22:44 UTC, kengdoj commented on testcases/TC8.1-2-fail-4.md
> +| 8.1-1| Determine the contrast ratio of foreground and background in the image of text. | The contrast ratio for the text is 4.5:1 |
the last column for the result should explain the actual contrast ratio.

2021-11-17 22:45 UTC, kengdoj commented on testcases/TC8.1-2-fail-4.md
> +| 8.1-2| Check that the contrast ratio is at least 4.5:1. [SC 3.14] | The contrast ratio is more than 4.5:1 (it is 2.6:1) |
if the contrast ratio is 2.6:1, it is less.

2021-11-17 22:46 UTC, kengdoj commented on testcases/TC8.1-2-fail-4.md
> +| 8.1-2| Check that the contrast ratio is at least 4.5:1. [SC 3.14] | The contrast ratio is more than 4.5:1 (it is 2.6:1) |
Also please correct the SC number.

2021-11-17 22:48 UTC, kengdoj commented on testcases/TC8.1-2-fail-4.md
> +| Results | Both of the above checks fail, then Baseline Test 8.1-Contrast Minimum.  | Fail |
Copy the result from the Baseline Test Results for the second column: 
| | If both of the above checks fail, then Baseline Test 8.1-ContrastMinimum fails | Fail: then your explanation |

2021-11-17 22:49 UTC, kengdoj commented on testcases/TC8.1-2-fail-4.md
> +sample: /testfiles/TF08/08.1-2-fail-4.html
Is this file in a different PR?

2021-11-17 22:50 UTC, kengdoj requested changes
Thanks, Cecilia! Please see comments.

2022-02-10 17:36 UTC, kengdoj requested changes

2022-02-10 17:36 UTC, kengdoj commented on testcases/TC8.1-2-fail-4.md
> +  **Test Instruction:** 1
the filename indicates this would be for instruction 2. Can you double check?

2022-02-23 16:25 UTC, CJStegall commented on TC8.1-3-pass-2
> +app-basline:|[8.1 Test Procedure for Contrast Minimum]https://section508coordinators.github.io/ICTTestingBaseline/08Contrast.html#81-test-procedure-for-contrast-minimum
Nope the typo is not in the original template.

2022-02-23 16:52 UTC, CJStegall commented on TC8.1-3-pass-2
> +app-basline:|[8.1 Test Procedure for Contrast Minimum]https://section508coordinators.github.io/ICTTestingBaseline/08Contrast.html#81-test-procedure-for-contrast-minimum
Done

2022-02-23 16:52 UTC, CJStegall commented on TC8.1-3-pass-2
> +|IC| All visible text AND images of text (except those noted in Limitations, Assumptions, or Exceptions above)|
Done

2022-02-24 20:20 UTC, kengdoj commented on TC8.1-3-pass-2
> +|IC| All visible text AND images of text (except those noted in Limitations, Assumptions, or Exceptions above)|
I don't see "visible text found" in the last column for identify content.

2022-02-24 20:22 UTC, kengdoj commented on TC8.1-3-pass-2
> +  **Test Instruction:** 1
the filename has 8.1-3. Please check the instruction number?

2022-02-24 20:27 UTC, kengdoj commented on testfiles/TF08/08.1-3-pass-2.html
> +<body>
I don't see this change?

2022-02-24 20:32 UTC, kengdoj commented on testcases/TC8.1-2-fail-4.md
> +sample: /testfiles/TF08/08.1-2-fail-4.html
I can't approve this one without the test file.

2022-02-24 20:33 UTC, kengdoj submitted a review, later dismissed
please see comments.

2022-08-26 22:18 UTC, drewnielson approved these changes
Approved with edits

2022-08-26 22:18 UTC, merged